### ISSUE TITLE
Twitch icon problem 

### ISSUE THREAD

**Issue by lebjulien** [amarcu5/PiPer#120]
<img width="369" alt="Capture d’écran 2021-08-10 à 17 03 34" src="https://user-images.githubusercontent.com/65189374/128891351-aa957ccd-8163-46ef-a80c-088857163bef.png">

**Comment by Nosgoroth** [comment]
Same issue here in Safari. I added this CSS to a user stylesheet (using Cascadea)  and that seems to have done it, but I'd rather a fix was applied to the extension itself.

```css
#PiPer_button {
	max-width: 30px;
}
#PiPer_button .tw-tooltip {
    display: none;
}
```
